version: "3.7"

networks:
  default:
    name: traff
    external: true

services:
  erp-backend-dev:
    container_name: "erp-backend-dev"
    image: neobytesolutions/erp-backend:dev
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - traefik.enable=true
      - traefik.http.routers.erp-backend-dev.rule=Host(`dev-api.optimanage.ro`)
      - traefik.port=80
      - traefik.docker.network=traff
      - traefik.http.routers.erp-backend-dev.tls=true
      - traefik.http.routers.erp-backend-dev.tls.certresolver=myresolver
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      - traefik.http.routers.erp-backend-dev.middlewares=https-redirect


    environment:
      - POSTGRES_SSL_CERT=../certificate.pem
      - POSTGRES_DB_HOST=$POSTGRES_DB_HOST
      - POSTGRES_DB_PORT=$POSTGRES_DB_PORT
      - POSTGRES_DB_USER=$POSTGRES_DB_USER
      - POSTGRES_DB_PASSWORD=$POSTGRES_DB_PASSWORD
      - POSTGRES_DB_NAME=$POSTGRES_DB_NAME
      - EFACTURA_CLIENT_ID=$EFACTURA_CLIENT_ID
      - EFACTURA_CLIENT_SECRET=$EFACTURA_CLIENT_SECRET
      - EFACTURA_CALLBACK_URL=$EFACTURA_CALLBACK_URL
      - EFACTURA_CALLBACK_PATH=$EFACTURA_CALLBACK_PATH
      - EFACTURA_AUTHORIZATION_REDIRECT_URL=$EFACTURA_AUTHORIZATION_REDIRECT_URL

    env_file: ./.env

  erp-app-live:
    container_name: "erp-api-live"
    build:
      context: .
      dockerfile: Dockerfile
    image: erp-api:live
    # ports:
    #   - "8080:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.erp-api-live.rule=Host(`api.optimanage.ro`)"
      - "traefik.port=80"
      - "traefik.docker.network=traff"

    environment:
      - POSTGRES_SSL_CERT=../certificate.pem
      - POSTGRES_DB_HOST=$POSTGRES_DB_HOST
      - POSTGRES_DB_PORT=$POSTGRES_DB_PORT
      - POSTGRES_DB_USER=$POSTGRES_DB_USER
      - POSTGRES_DB_PASSWORD=$POSTGRES_DB_PASSWORD
      - POSTGRES_DB_NAME=$POSTGRES_DB_NAME
      - EFACTURA_CLIENT_ID=$EFACTURA_CLIENT_ID
      - EFACTURA_CLIENT_SECRET=$EFACTURA_CLIENT_SECRET
      - EFACTURA_CALLBACK_URL=$EFACTURA_CALLBACK_URL
      - EFACTURA_CALLBACK_PATH=$EFACTURA_CALLBACK_PATH
      - EFACTURA_AUTHORIZATION_REDIRECT_URL=$EFACTURA_AUTHORIZATION_REDIRECT_URL

    env_file: ./.env


  erp-frontend-dev:
    container_name: "erp-frontend-dev"
    image: neobytesolutions/erp-frontend:dev
    restart: unless-stopped
    build:
      context: ../frontend
      dockerfile: frontend/Dockerfile
      args:
          - BRANCH=dev
    labels:
      - traefik.enable=true
      - traefik.http.routers.erp-frontend-dev.rule=Host(`dev.optimanage.ro`)
      - traefik.port=80
      - traefik.docker.network=traff
      # - traefik.http.routers.erp-frontend-dev.entrypoints=websecure
      - traefik.http.routers.erp-frontend-dev.tls=true
      - traefik.http.routers.erp-frontend-dev.tls.certresolver=myresolver
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      - traefik.http.routers.erp-frontend-dev.middlewares=https-redirect


  erp-frontend-live:
    container_name: "erp-frontend-live"
    build:
      context: ../frontend
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.erp-frontend-live.rule=Host(`optimanage.ro`)"
      - "traefik.port=80"
      - "traefik.docker.network=traff"


