version: "3.7"
services:
  netopia-app:
    container_name: "netopia-api"
    build:
      context: .
      dockerfile: Dockerfile
    image: netopia-api:latest
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_SSL_CERT=../certificate.pem
      - POSTGRES_DB_HOST=db-postgresql-ams3-03234-do-user-15103733-0.m.db.ondigitalocean.com
      - POSTGRES_DB_PORT=25060
      - POSTGRES_DB_USER=doadmin
      - POSTGRES_DB_PASSWORD=AVNS_krl7n3uDLGw6cUFMJfU
      - POSTGRES_DB_NAME=prod

#    depends_on:
#      - erp-postgres
    env_file: ./.env

  erp-frontend:
    container_name: "erp-frontend"
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"