version: "3.7"
services:
  netopia-app:
    container_name: "netopia-api"
    build:
      context: .
      dockerfile: Dockerfile
    image: netopia-api:latest
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_SSL_CERT=../certificate.pem
      - POSTGRES_DB_HOST=$POSTGRES_DB_HOST
      - POSTGRES_DB_PORT=$POSTGRES_DB_PORT
      - POSTGRES_DB_USER=$POSTGRES_DB_USER
      - POSTGRES_DB_PASSWORD=$POSTGRES_DB_PASSWORD
      - POSTGRES_DB_NAME=$POSTGRES_DB_NAME

#    depends_on:
#      - erp-postgres
    env_file: ./.env

  erp-frontend:
    container_name: "erp-frontend"
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"