// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: chart.sql

package db

import (
	"context"
)

const getActualVsLastYearSales = `-- name: GetActualVsLastYearSales :many
SELECT month::text, amount_this_year::float, amount_last_year::float  FROM core.get_sales_actual_vs_last()
`

type GetActualVsLastYearSalesRow struct {
	Month          string
	AmountThisYear float64
	AmountLastYear float64
}

func (q *Queries) GetActualVsLastYearSales(ctx context.Context) ([]GetActualVsLastYearSalesRow, error) {
	rows, err := q.db.Query(ctx, getActualVsLastYearSales)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActualVsLastYearSalesRow
	for rows.Next() {
		var i GetActualVsLastYearSalesRow
		if err := rows.Scan(&i.Month, &i.AmountThisYear, &i.AmountLastYear); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
