// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: company.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getCompany = `-- name: GetCompany :one
SELECT id,
       name,
       vat,
       vat_number,
       registration_number,
       address,
       locality,
       county_code,
       email,
       bank_name,
       bank_account,
       frontend_url
from core.company
    LIMIT 1
`

type GetCompanyRow struct {
	ID                 uuid.UUID
	Name               string
	Vat                bool
	VatNumber          string
	RegistrationNumber sql.NullString
	Address            string
	Locality           sql.NullString
	CountyCode         sql.NullString
	Email              sql.NullString
	BankName           sql.NullString
	BankAccount        sql.NullString
	FrontendUrl        sql.NullString
}

func (q *Queries) GetCompany(ctx context.Context) (GetCompanyRow, error) {
	row := q.db.QueryRow(ctx, getCompany)
	var i GetCompanyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Vat,
		&i.VatNumber,
		&i.RegistrationNumber,
		&i.Address,
		&i.Locality,
		&i.CountyCode,
		&i.Email,
		&i.BankName,
		&i.BankAccount,
		&i.FrontendUrl,
	)
	return i, err
}
