// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
)

type CoreDepartment struct {
	ID    int32
	Name  string
	Flags sql.NullInt32
}

type CoreDepartmentRelationship struct {
	ParentID int32
	ChildID  int32
}
