// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DepartmentInput struct {
	ID         *int   `json:"id,omitempty"`
	Name       string `json:"name"`
	Flags      int    `json:"flags"`
	ParentsIds []int  `json:"parents_ids,omitempty"`
}

type Mutation struct {
}

type Query struct {
}
