import 'package:erp_frontend_v2/models/app_localizations.dart';
import 'package:flutter/material.dart';

extension BuildContextExtensions on BuildContext {
  Size get deviceSize => MediaQuery.of(this).size;
  double get deviceWidth => deviceSize.width;
  double get deviceHeight => deviceSize.height;
  double get width01 => deviceWidth * 0.01;
  double get width02 => deviceWidth * 0.02;
  double get width03 => deviceWidth * 0.03;
  double get width04 => deviceWidth * 0.04;
  double get width05 => deviceWidth * 0.05;
  double get width10 => deviceWidth * 0.1;
  double get width15 => deviceWidth * 0.15;
  double get width20 => deviceWidth * 0.2;
  double get width25 => deviceWidth * 0.25;
  double get width30 => deviceWidth * 0.3;
  double get width35 => deviceWidth * 0.35;
  double get width40 => deviceWidth * 0.4;
  double get width45 => deviceWidth * 0.45;
  double get width50 => deviceWidth * 0.5;
  double get width55 => deviceWidth * 0.55;
  double get width60 => deviceWidth * 0.6;
  double get width65 => deviceWidth * 0.65;
  double get width70 => deviceWidth * 0.7;
  double get width75 => deviceWidth * 0.75;
  double get width80 => deviceWidth * 0.8;
  double get width85 => deviceWidth * 0.85;
  double get width90 => deviceWidth * 0.9;
  double get width95 => deviceWidth * 0.95;
  double get height01 => deviceHeight * 0.01;
  double get height02 => deviceHeight * 0.02;
  double get height03 => deviceHeight * 0.03;
  double get height04 => deviceHeight * 0.04;
  double get height05 => deviceHeight * 0.05;
  double get height10 => deviceHeight * 0.1;
  double get height15 => deviceHeight * 0.15;
  double get height20 => deviceHeight * 0.2;
  double get height25 => deviceHeight * 0.25;
  double get height30 => deviceHeight * 0.3;
  double get height35 => deviceHeight * 0.35;
  double get height40 => deviceHeight * 0.4;
  double get height45 => deviceHeight * 0.45;
  double get height50 => deviceHeight * 0.5;
  double get height55 => deviceHeight * 0.55;
  double get height60 => deviceHeight * 0.6;
  double get height65 => deviceHeight * 0.65;
  double get height70 => deviceHeight * 0.7;
  double get height75 => deviceHeight * 0.75;
}
