
CREATE SCHEMA IF NOT EXISTS core;

CREATE TABLE IF NOT EXISTS core.users(
    id TEXT PRIMARY KEY UNIQUE,
    phone_number VARCHAR(20) NULL,
    name VARCHAR(50)  NULL,
    email VARCHAR(50) NOT NULL UNIQUE
);

