version: "3.8"

services:
  proxi:
    image: traefik:v3.0
    restart: always
    container_name: traefik
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    command:
      - --api.insecure=true
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker.network=traff
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --certificatesresolvers.myresolver.acme.email=lilianpletosu7@gmail.com
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt/:/letsencrypt
    networks:
      - traff

networks:
  traff:
    name: traff

