name: Build and Deploy Live

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.22.2'

    - name: Install dependencies
      run: flutter pub get

    - name: Build web
      run: flutter build web --release --web-renderer canvaskit

    - name: Build Docker image
      run: docker build -t liliancik098/flutter_live:latest -f flutter-app/live/Dockerfile .

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Push Docker image
      run: docker push liliancik098/flutter_live:latest

    - name: Deploy to Server
      run: ssh ubuntu@159.223.234.127 "docker pull liliancik098/flutter_live:latest && docker-compose -f backend/docker-compose.yml up -d erp-api-live erp-frontend-live"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
