name: Build and Deploy Testing

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.22.2'

    - name: Navigate to frontend
      run: |
        cd frontend
        flutter pub get
        flutter build web --release --web-renderer canvaskit

    - name: Build Docker image for frontend
      run: |
        cd frontend
        docker build -t liliancik098/flutter_testing:latest -f frontend/testing/Dockerfile .

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Push Docker image
      run: docker push liliancik098/flutter_testing:latest

    - name: Deploy to Server
      run: ssh ubuntu@159.223.234.127 "docker pull liliancik098/flutter_testing:latest && docker-compose -f backend/docker-compose.yml up -d erp-api-dev erp-frontend-dev"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
